browserName=chrome
appURL=https://tutorialsninja.com/demo/
firstName=arun
lastName=Motoori
telephoneNumber=1234567890
InvalidTelephone=abcde
validPassword=12345
mismatchingPassword=67890
existingEmail=tanveertannu005@gmail.com
InvalidEmailOne=amotoori1
InvalidEmailTwo=amototi@
InvalidEmailThree=amotoori@gmail
InvalidEmailFour=amotoori@gmail.
RegisterPageUrl=https://tutorialsninja.com/demo/index.php?route=account/register
