#Updated properties file
#Wed Apr 22 23:56:35 IST 2026
InvalidEmailOne=amotoori1
lastName=Motoori
mismatchingPassword=67890
telephoneNumber=1234567890
RegisterPageUrl=https\://tutorialsninja.com/demo/index.php?route\=account/register
loginPageUrl=https://tutorialsninja.com/demo/index.php?route=account/login
logOutPageUrl=https://tutorialsninja.com/demo/index.php?route=account/logout
InvalidEmailTwo=amototi@
inactiveEmail=amotooricap123454321@gmail.com
randomPasword=a@123$45
validPasswordThree=Admin@123
appURL=https\://tutorialsninja.com/demo/
firstName=arun
NonExistingEmail=xyzabc12**667@\#\#3@gmail.com
InvalidEmailFour=amotoori@gmail.
InvalidEmailThree=amotoori@gmail
browserName=edge
validEmail=tanveertannu00150@yopmail.com
validPassword=admin
InvalidTelephone=abcde
validPasswordTwo=admin1234
existingEmail=anayaxyze4il0@yopmail.com
existingProduct=HP
NonexistingProduct=Fitbit
